#
# RUN JSHINT & QUNIT TESTS IN PHANTOMJS
#
outfile = AVAILABLE_STEPS.txt

test:
	node steptesting/server.js &
	cucumber 
	kill -9 `cat steptesting/pid.txt`
	rm steptesting/pid.txt

install:
	cd steptesting && npm install && cd -
	echo "node modules successfully installed in steptesting/node_modules"
	echo
	echo "run tests by typing 'make test'"



server_start:
	node steptesting/server.js &

server_stop:
	kill -9 `cat steptesting/pid.txt`
	rm steptesting/pid.txt


# creates list of available steps from the step definitions file
stepdefs:
	cat /dev/null > ${outfile}
	echo "AUTOGENERATED.  by 'make stepdefs' " >> ${outfile}
	echo >> ${outfile}
	echo "AVAILABLE STEP DEFINITIONS"  >> ${outfile}
	echo "==========================" >> ${outfile}
	cucumber -p stepdefs -q | grep "/^" >> ${outfile}
	echo >> ${outfile}
	echo >> ${outfile}
	echo >> ${outfile}
	echo "UNUSED STEP DEFINITIONS"  >> ${outfile}
	echo "==========================" >> ${outfile}
	cucumber -p stepdefs -q | grep -B 1 "NOT MATCHED" | grep -v -e "NOT MATCHED" -o -e "--" >> ${outfile}
	echo >> ${outfile}


